units:
  globalOffset_x: 100
  globalOffset_y: -150


  pad: 2

  ctrl_height: 18.5 
  ctrl_width: 33.5

  px: cx + pad
  py: cy + pad

  push_x: px / 2
  push_y: py / 2

  pad_x: push_x + pad
  pad_y: push_y + pad

  spacing: .75

  tr_bias: 20
  tr_margin_x: 16
  tr_margin_y: -38

  ot_fillet: 1

  k_width: 18
  k_height: 17
  

points:
  zones:
    matrix:
      key:
        padding: cx + spacing
        spread: cy + spacing
      columns:
        pinky:
          key:
            column_net: P020
        ring:
          key:
            column_net: P022
            stagger: 8
        middle:
          key:
            column_net: P024
            stagger: 2.5
        index:
          key:
            column_net: P100
            stagger: -2.5
        inner:
          key:
            column_net: P011
            stagger: -1
      rows:
        bottom:
          row_net: P113
        home:
          row_net: P115
        top:
          row_net: P002
      anchor: 
        shift: [globalOffset_x, globalOffset_y]
    thumbs:
      anchor:
        ref: matrix_index_home
        rotate: -tr_bias
        shift: [tr_margin_x, tr_margin_y]
      columns:
        inner:
          key:
            rotate: tr_bias
            shift: [-8, -5]
            column_net: P111
        home:
          key:
            column_net: P009
        outer:
          key:
            rotate: -5
            shift: [10.5, 0]
            column_net: P010
      rows:
        cluster:
          row_net: P017

outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0
  left:
    # - where: true
    #   what: rectangle
    #   size: [cx + 1, cy + 1]
    #   fillet: ot_fillet
    - what: polygon
      fillet: ot_fillet
      points:
        - ref: matrix_index_bottom
          shift: [-3.3, -k_width / 2]
        - ref: thumbs_inner_cluster
          shift: [-k_height / 2, -k_width / 2]
        - ref: thumbs_inner_cluster
          shift: [k_height / 2, -k_width / 2]
        - ref: thumbs_home_cluster
          shift: [-k_height / 2, -k_width / 2]
        - ref: thumbs_home_cluster
          shift: [k_height / 2, -k_width / 2]
        - ref: thumbs_outer_cluster
          shift: [-k_height / 2, -k_width / 2]
        - ref: thumbs_outer_cluster
          shift: [k_height / 2, -k_width / 2]
        - ref: thumbs_outer_cluster
          shift: [k_height / 2, k_width / 2]
        - ref: thumbs_outer_cluster
          shift: [-k_height / 2, k_width / 2]
        - ref: matrix_inner_top
          shift: [34, -42]
        - ref: matrix_inner_top
          shift: [34, k_width / 2]
        - ref: matrix_inner_top
          shift: [0, k_width / 2]
#     - what: polygon
#       fillet: ot_fillet
#       points:
#         - ref: matrix_inner_top
#           shift: [0, 9]
#         - ref: matrix_inner_top
#           shift: [33, 9] 
#         - ref: matrix_inner_top
#           shift: [33, -30]
#         # - ref: thumbs_outer_cluster
#         #   shift: [2, 12]
#         - ref: thumbs_outer_cluster
#           shift: [10, 12]
#         - ref: thumbs_outer_cluster
#           shift: [12, -12]
#         - ref: thumbs_inner_cluster
#           shift: [-10, -10]
#         - ref: matrix_pinky_bottom
#           shift: [-9, -9]
#         # - ref: matrix_inner_bottom
#         #   shift: [42, -9]
#         # - ref: matrix_inner_bottom
#         #   shift: [0, -9]

pcbs:
  left:
    outlines:
      main:
        outline: left
    footprints:
      choc_hotswaps:
        what: choc
        where: /^(matrix_|thumbs_).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^(matrix_|thumbs_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]
          rotate: 90
      battery_jack:
        what: jstph
        where:
          ref: matrix_inner_top
          shift: [22 + ctrl_width / 2, -13 - ctrl_height]
        params:
          pos: pos
          neg: GND
      reset:
        what: EVQPUC
        where:
          ref: matrix_inner_top
          shift: [33, -16 - ctrl_height]
        params:
          from: GND
          to: RST
      battery_switch:
        what: slider
        where:
          ref: matrix_inner_top
          shift: [33, -20 - ctrl_height]
        params:
          from: pos
          to: RAW

      # keyswitches:
      #   where: true
      #   what: choc
      #   params:
      #     hotswap: true
      #     from: "{{col_net}}"
      #     to: "{{colrow}}"
      nice_nano:
        what: nice_nano
        where:
          ref: matrix_inner_top
          shift: [22, -10]
          rotate: 90
      front_text: &text
        what: text
        where: &textWhere
            ref: matrix_inner_top
            shift: [31, k_height / 2 - 1.5]
        params: &textParams
            text: ARC-T
            justify: right
            h_size: 1.5
            v_size: 1.5
            thickness: 0.2