units:
  globalOffset_x: 100
  globalOffset_y: -150

  stagger_ring: 8
  stagger_middle: 2.5
  stagger_index: -2.5
  stagger_inner: -1

  pad: 2

  ctrl_height: 18.5 
  ctrl_width: 33.5

  px: cx + pad
  py: cy + pad

  push_x: px / 2
  push_y: py / 2

  pad_x: push_x + pad
  pad_y: push_y + pad

  spacing: .75

  spaceInsideOfKeys: 24.5

  tr_bias: 20
  tr_margin_x: 16
  tr_margin_y: -38

  ot_fillet: 2
  

points:
  zones:
    matrix:
      key:
        padding: cy + spacing
        spread: cx + spacing
      columns:
        pinky:
          key:
            column_net: P020
        ring:
          key:
            column_net: P022
            stagger: stagger_ring
        middle:
          key:
            column_net: P024
            stagger: stagger_middle
        index:
          key:
            column_net: P100
            stagger: stagger_index
        inner:
          key:
            column_net: P011
            stagger: stagger_inner
      rows:
        bottom:
          row_net: P113
        home:
          row_net: P115
        top:
          row_net: P002
      anchor: 
        shift: [globalOffset_x, globalOffset_y]
    thumbs:
      anchor:
        ref: matrix_index_home
        rotate: -tr_bias
        shift: [tr_margin_x, tr_margin_y]
      columns:
        inner:
          key:
            rotate: tr_bias
            shift: [-8, -5]
            column_net: P111
        home:
          key:
            column_net: P009
        outer:
          key:
            rotate: -5
            shift: [10.5, 0]
            column_net: P010
      rows:
        cluster:
          row_net: P017

outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0
  left:
    - what: polygon
      operation: stack
      fillet: ot_fillet
      points:
        - ref: matrix_inner_bottom
          shift: [pad_x + spaceInsideOfKeys, -pad_y - 8.5]
        - ref: matrix_inner_top
          shift: [pad_x + spaceInsideOfKeys, pad_y - stagger_inner - stagger_index]
        - ref: matrix_middle_top
          shift: [pad_x, pad_y]
        - ref: matrix_middle_top
          shift: [-pad_x, pad_y]
        - ref: matrix_middle_top
          shift: [-pad_x, pad_y - stagger_middle]
        - ref: matrix_ring_top
          shift: [-pad_x, pad_y]
        - ref: matrix_ring_top
          shift: [-pad_x, pad_y - stagger_ring]
        - ref: matrix_pinky_top
          shift: [-pad_x, pad_y]
        - ref: matrix_pinky_bottom
          shift: [-pad_x, -pad_y]
        - ref: matrix_pinky_bottom
          shift: [pad_x, -pad_y]
        - ref: matrix_pinky_bottom
          shift: [pad_x, -pad_y + stagger_ring]
        - ref: thumbs_inner_cluster
          shift: [-pad_x, push_y + 1.215]
        - ref: thumbs_inner_cluster
          shift: [-pad_x, -pad_y]
        - ref: thumbs_inner_cluster
          shift: [pad_x, -pad_y]
        - ref: thumbs_home_cluster
          shift: [pad_x, -pad_y]
        - ref: thumbs_outer_cluster
          shift: [pad_x, -pad_y]
        - ref: thumbs_outer_cluster
          shift: [pad_x, pad_y]

pcbs:
  left:
    outlines:
      main:
        outline: left
    footprints:
      choc_hotswaps:
        what: choc
        where: /^(matrix_|thumbs_).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^(matrix_|thumbs_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]
          rotate: 90
      battery_jack:
        what: jstph
        where:
          ref: matrix_inner_bottom
          shift: [push_x + .75 * spaceInsideOfKeys, 0]
          rotate: -90
        params:
          pos: pos
          neg: GND
      reset:
        what: EVQPUC
        where:
          ref: matrix_inner_bottom
          shift: [spaceInsideOfKeys + push_x - .5 * spacing, 0]
          rotate: -90
        params:
          from: GND
          to: RST
      battery_switch:
        what: slider
        where:
          ref: matrix_inner_bottom
          shift: [spaceInsideOfKeys + push_x - .5 * spacing, -8.5]
          rotate: -90
        params:
          from: pos
          to: RAW
      nice_nano:
        what: nice_nano
        where:
          ref: matrix_inner_top
          shift: [push_x + (spaceInsideOfKeys / 2) + .6, -.5 * ctrl_width + push_y + .53]
          rotate: 90
      front_text: &text
        what: text
        where: &textWhere
            ref: matrix_inner_top
            shift: [push_x + (spaceInsideOfKeys + ctrl_height) / 2, pad_y]
        params: &textParams
            text: ARC-T
            justify: right
            h_size: 1.5
            v_size: 1.5
            thickness: 0.2